repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    # Git style
    - id: check-added-large-files
    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
- repo: local
  hooks:
    - id: terraform_fmt
      name: terraform_fmt
      entry: /tmp/pre-commit-config/terraform_fmt.sh
      language: script
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$
    - id: terraform_docs_without_aggregate_type_defaults
      name: Terraform docs (without aggregate type defaults)
      description: Inserts input and output documentation into README.md (using terraform-docs). Identical to terraform_docs.
      require_serial: true
      entry: /tmp/pre-commit-config/terraform_docs.sh
      language: script
      files: (\.tf)$
      exclude: \.terraform\/.*$
    - id: terraform_validate
      name: Terraform validate
      description: Validates all Terraform configuration files.
      require_serial: true
      entry: /tmp/pre-commit-config/terraform_validate.sh
      language: script
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$
    - id: terraform_tflint
      name: Terraform validate with tflint
      description: Validates all Terraform configuration files with TFLint.
      entry: /tmp/pre-commit-config/terraform_tflint.sh
      language: script
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$
    - id: terraform_tfsec
      name: Terraform validate with tfsec
      description: Static analysis of Terraform templates to spot potential security issues.
      entry: /tmp/pre-commit-config/terraform_tfsec.sh
      language: script
    - id: terrascan
      name: terrascan
      description: Runs terrascan on Terraform templates.
      language: script
      entry: /tmp/pre-commit-config/terrascan.sh
